# Generated by Django 5.1.5 on 2025-01-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllowedApi",
            fields=[
                (
                    "record_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("comment", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Допустимі ip адреси",
                "db_table": "api_allowed_keys",
            },
        ),
        migrations.CreateModel(
            name="ApiReqLog",
            fields=[
                (
                    "record_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("headers", models.BinaryField()),
                ("body", models.BinaryField()),
                ("ip_address", models.CharField(max_length=20)),
                ("date", models.DateTimeField()),
            ],
            options={
                "verbose_name_plural": "Лог запитів до апі",
                "db_table": "api_requests_log",
            },
        ),
    ]
