# Generated by Django 5.1.5 on 2025-02-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allowedapi",
            options={"verbose_name_plural": "Допустимі api key"},
        ),
        migrations.RemoveField(
            model_name="allowedapi",
            name="ip_address",
        ),
        migrations.AddField(
            model_name="allowedapi",
            name="api_key",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
