# Generated by Django 5.1.5 on 2025-01-25 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "record_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("status_code", models.CharField(max_length=100, unique=True)),
                ("status_title", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статуси",
                "db_table": "data_status",
            },
        ),
        migrations.CreateModel(
            name="TgChat",
            fields=[
                (
                    "record_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "chat_tg_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID чата в Telegram"
                    ),
                ),
                (
                    "chat_title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Название чата",
                    ),
                ),
                (
                    "chat_user_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Username чата",
                    ),
                ),
                (
                    "transaction_target",
                    models.BooleanField(
                        default=False,
                        verbose_name="Публікуйте applications в цьому чаті",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram чат",
                "verbose_name_plural": "Telegram чати",
                "db_table": "tg_chat",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("user_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "senior_operator",
                    models.BooleanField(default=False, verbose_name="Старший оператор"),
                ),
                (
                    "bot_admin",
                    models.BooleanField(
                        default=False, verbose_name="Адміністратор бота"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Користувачі бота",
                "db_table": "data_tg_user",
            },
        ),
        migrations.CreateModel(
            name="ExchangeTransaction",
            fields=[
                (
                    "uuid",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("external_order_id", models.CharField(max_length=100)),
                ("currency", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "currency_xml_code",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("amount", models.FloatField()),
                ("full_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "card_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("posted_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admin_panel.status",
                    ),
                ),
                (
                    "posted_in_chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admin_panel.tgchat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на обмін",
                "verbose_name_plural": "Заявки на обмін",
                "db_table": "exchange_transaction",
            },
        ),
    ]
