# Generated by Django 5.1.5 on 2025-01-25 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_exchangetransaction_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangetransaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
