# Generated by Django 5.1.5 on 2025-02-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_exchangetransaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetransaction',
            name='usdt_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangetransaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
