# Generated by Django 5.1.5 on 2025-11-12 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_exchangetransaction_usdt_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangetransaction",
            name="iban",
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name="exchangetransaction",
            name="inn",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="exchangetransaction",
            name="method_type",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exchangetransaction",
            name="payment_note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exchangetransaction",
            name="payout_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="exchangetransaction",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exchangetransaction",
            name="revtag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="exchangetransaction",
            name="service_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="exchangetransaction",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_transactions",
                to="admin_panel.user",
            ),
        ),
        migrations.AlterField(
            model_name="exchangetransaction",
            name="posted_in_chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="admin_panel.tgchat",
            ),
        ),
        migrations.AlterField(
            model_name="exchangetransaction",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="admin_panel.status",
            ),
        ),
    ]
