# Generated by Django 5.1.5 on 2026-01-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_exchangetransaction_iban_exchangetransaction_inn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetransaction',
            name='rates',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
